update and readme

diff --git a/base/dot-local/bin/stap b/base/dot-local/bin/stap
--- a/base/dot-local/bin/stap
+++ b/base/dot-local/bin/stap
@@ -1,15 +1,15 @@
 #!/usr/bin/env fish
 
 function print_help
-    echo "Usage: stap [-p PATH] [apps...]"
+    echo "Usage: stap app1 apps2 [-p your dotfiles forder path]"
     echo ""
     echo "Options:"
-    echo "  -p, --path PATH     Path to your dotfiles directory (required once per system)"
+    echo "  -p, --path PATH     Path to your dotfiles directory (required once)"
     echo "  -h, --help          Show this help message and exit"
     echo ""
     echo "Examples:"
-    echo "  stap -p ~/.dotfiles necessary"
-    echo "  stap hyprland gtk kitty"
+    echo "  stap -p ~/.dotfiles"
+    echo "  stap base hyprland gtk kitty"
 end
 
 function print_apps
@@ -26,7 +26,7 @@ set -l i 1
 while test $i -le (count $argv)
     set arg $argv[$i]
 
-    if test \($arg = "-p"\) -o \($arg = "--path"\)
+    if test $arg = "-p" || test $arg = "--path"\)
         set -l next_index (math $i + 1)
         if test $next_index -gt (count $argv)
             echo "Error: Missing argument for $arg"
@@ -35,8 +35,9 @@ while test $i -le (count $argv)
 
         set -U dots_path (realpath (string replace -r '^~' $HOME $argv[$next_index]))
 
-        set argv (remove $i $next_index $argv)
-        continue # no incrementation because argv is shorter
+        set -e argv[$i]
+        set -e argv[$i]
+        continue
     end
 
     if test $arg = "-h" || test $arg = "--help"
@@ -51,16 +52,17 @@ while test $i -le (count $argv)
 end
 
 if not set -q dots_path
-    echo "Please set your dotfiles folder: stap -p path"
+    echo "No dotfiles path given, defaulting to ~/.dotfiles"
+    set -U dots_path $HOME/.dotfiles
     exit
 end
 
 # Apply stow
 for a in $argv
-    if test $a = "necessary"
-        stow --dotfiles --dir $dots_path --target ~ -S necessary
+    if test $a = "base"
+      stow -v --dotfiles --dir "$dots_path" --target ~ -S $a
     else
-        stow --dotfiles --dir $dots_path/apps --target ~ -S $a
+      stow -v --dotfiles --dir "$dots_path/apps" --target ~ -S $a
     end
 end
 
